// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using distanceapi.Models;

namespace distanceapi.Migrations
{
    [DbContext(typeof(DistanceDbContext))]
    [Migration("20211122124638_disttbl")]
    partial class disttbl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("distanceapi.Models.distance", b =>
                {
                    b.Property<int>("distance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("To_place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("dist")
                        .HasColumnType("real");

                    b.Property<float>("from_loc_lat")
                        .HasColumnType("real");

                    b.Property<float>("from_loc_lng")
                        .HasColumnType("real");

                    b.Property<string>("from_place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("to_location_lat")
                        .HasColumnType("real");

                    b.Property<float>("to_location_lng")
                        .HasColumnType("real");

                    b.HasKey("distance_id");

                    b.ToTable("GetDistances");
                });
#pragma warning restore 612, 618
        }
    }
}
